schema_version = "1.0.0"

id = "pivotier"
version = "2.0.0"
name = "Pivotier"
tagline = "Enhanced object alignment and pivot point management"
maintainer = "jhmorel <jhmorel11art@gmail.com>"
type = "add-on"

website = "https://github.com/jhmorel/Pivotier"
tags = ["Object", "Mesh"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2025 Javier Hernández Morel",
]
